### ISSUE TITLE
首頁文章預覽圖被強制拉伸、頁面導覽列異常

### ISSUE THREAD

**Issue by candy999** [gnehs/Carter#1]
http://i.imgur.com/6uEq0MX.jpg

**Comment by gnehs** [comment]
![1496572409 0604 1833](https://cloud.githubusercontent.com/assets/16719720/26760823/88f4c392-4954-11e7-8bb8-cdaf5df5edd5.png)
強制拉伸的情況可能是您所安裝的外掛所導致的，我自己測試時沒問題，預計在下個版本修正

![1496572485 0604 1834](https://cloud.githubusercontent.com/assets/16719720/26760830/b1d71508-4954-11e7-80ae-57ec5e77fd89.png)
導覽列異常的部分，麻煩到選單設定一下，這點忘記寫進 README 了 😂

**Comment by candy999** [comment]
雖然最後自己這樣來解~哈哈
.ts.card>.image img {
    height: inherit;
}

**Comment by gnehs** [comment]
我這樣搞欸
然後有新版了，要用的話記得下載
```
.ts.card>.image img {
    height: auto !important;
}
```

**Comment by lekoOwO** [comment]
我也有這個問題QQ
套用1.5.2版已修正，謝謝。
