### ISSUE TITLE
wordpress php exception in functions.php

### ISSUE THREAD

**Issue by sooxt98** [gnehs/Carter#11]
哎呀，我debug了整天还以为是我server问题，原来。。。
![image](https://user-images.githubusercontent.com/13378059/28779257-0be49fd6-7635-11e7-8cd9-ca2763fd1cf5.png)

**Comment by gnehs** [comment]
我大概知道問題在哪裡了，修正中

**Comment by gnehs** [comment]
@sooxiaotong 你再試試看
https://github.com/gnehs/Carter/archive/master.zip
