### ISSUE TITLE
請問頁尾文字能夠自訂嗎？

### ISSUE THREAD

**Issue by huangz92** [gnehs/Carter#14]
「Copyright」那一行字。因為網站打算使用不同的授權條款，所以想要更改頁尾文字。目前有試過修改 language/zh_TW.po ，但是沒有作用。

**Comment by gnehs** [comment]
可以直接修改 footer.php
https://github.com/gnehs/Carter/blob/42eadd9a7bdcc75ea7936d6ab2d679e503d7ab61/footer.php#L25
