### ISSUE TITLE
未來有打算提供header圖片上傳與深色主題嗎?

### ISSUE THREAD

**Issue by candy999** [gnehs/Carter#2]
未來有打算提供header圖片上傳與深色主題嗎?
另外header標題是否能提供回首頁的功能~

**Comment by gnehs** [comment]
深色主題這點有點麻煩我再考慮看看
Header 圖片上傳是打算做啦，不過我不太熟 PHP，可能會晚點推出😺
Header 回首頁這點最近會弄好👍

**Comment by gnehs** [comment]
新增惹夜間模式(##
