### ISSUE TITLE
分類的文章數換行

### ISSUE THREAD

**Issue by candy999** [gnehs/Carter#3]
首頁編輯按鈕壞了，分類的文章數是刻意換行的嗎?
![image](https://cloud.githubusercontent.com/assets/2743971/26767451/c77a0a18-49d2-11e7-8e09-cdea6c452ca0.png)

**Comment by candy999** [comment]
恩...首頁編輯按鈕好了....重新整理會有瞬間看到壞掉的樣子?XD

**Comment by gnehs** [comment]
那個按鈕是用 JQ 載入 Class 的，所以會先等 JQ 載入完才載入
但是我 PHP 才剛起步🙈，所以，等我找到好的解決方案才會處理它

**Comment by gnehs** [comment]
分類的文章數我還在找解決方案中，只好請你暫時別開啟囉

**Comment by gnehs** [comment]
剛剛讀了官方文件，發現 編輯按鈕 這問題很好處理，已經修正好了

**Comment by gnehs** [comment]
@candy999 建議你不同的錯誤分開發 Issue 這樣我比較好處理😀

**Comment by gnehs** [comment]
![1496751189 0606 2013](https://cloud.githubusercontent.com/assets/16719720/26828599/d7573b0e-4af4-11e7-8cf2-40f19c47ede0.png)
新版默默地修正了 OuOb
