### ISSUE TITLE
內文圖片不被置中(右)所控制。

### ISSUE THREAD

**Issue by candy999** [gnehs/Carter#4]
img.aligncenter
無正常運作~

**Comment by gnehs** [comment]
對，因為我根本沒寫那些 CSS
等等來寫吧~

**Comment by gnehs** [comment]
![1496663572 0605 1952](https://cloud.githubusercontent.com/assets/16719720/26783039/ccd2a1cc-4a28-11e7-90d8-06da45c79b46.png)
修正了
